### PR TITLE
Update README.md - tips on how HomeKit handles sensors

### PR DESCRIPTION
**Pull request by cistearns**

### CODE REVIEW

**Comment by EHylands** [comment]
Hi,
This is a very detailed evaluation of Homebridge-Homekit accessories management, thank you !

I'm currently using Home App on iOS 16 and I have upgrade to the new Homekit architecture.

My security system accessories and sensors were added to Homekit a long time ago.

1- I don't see any sensor status while selecting Home view security summary

2- I have multiple leak sensors all around the house. As you say, they don't show up in Home view water summary, but they do show up in every room alarm sensor summary. A triggered leak sensor will push a critical notification to Home App (can't miss that water leak with 5 apple device screaming for your attention!!)

Could any of those different behaviour be explained by different iOS version when accessories were added and by current Homekit architecture version ?

**Comment by cistearns** [comment]
1- I'll update the wording to clarify that sensor status only shows sensors that are triggered/active. It won't show closed contacts or idle motion sensors. So if you have no sensors tripped you won't see anything in the summary either. 
2- I can also update the wording related to Water sensors.

I think it's kind of poor UI for apple to display an empty screen when the selected summary has nothing to show for sensors rather than some sort of indicator that all sensors are idle/closed/ok.

**Comment by EHylands** [comment]
> What I am curious about, does the Qolsys Flood Alarm map to an alarm stat in HomeKit for the Security device?
> 
> I'm not mapping my flood sensors, since I found having a water summary option always visible in the Home View annoying. 

Unfortunately I only tested leak sensors with my Bosch panel (same Homebridge code shared with 2 panels). Leak are configured to trigger the security system accessory.

In IQ2 plus panel, i read that the option to sound the alarm in case of water events is disabled by default.

If your water sensors are set to non reporting, you could test if enabling the water freeze siren temperature option on panel set the alarm in Homekit. Hopefully, we should get an Alarm Police event in log file.

**Comment by cistearns** [comment]
I finished making tweaks to the wording in the readme, so it should now cover the critical questions that might come up.

**Pull request merged**
